[package]
name = "nl"
version = "0.1.1"
authors = ["Evgeny Safronov <division494@gmail.com>"]
license = "LGPL-3.0"
description = "Linux nelink native binding (project in active development, just reserved a name)"

[dependencies]
byteorder = "1"
serde = "1"
serde_derive = "1"
